export const people = [
    {
        "adult": false, "also_known_as": []
        , "biography": "Lisa Ann Walter (born August 3, 1963) is an American actress, comedienne, writer and film producer. She has appeared in such films as the 1998 version of The Parent Trap, Bruce Almighty, Shall We Dance, and War of the Worlds as Cheryl. Walter also created and starred in the short-lived 1996-1997 sitcom, Life's Work. She was a judge on ABC's reality television series The Next Best Thing: Who Is the Greatest Celebrity Impersonator?. She also won for her charity in a celebrity edition of The Weakest Link.\n\nDescription above from the Wikipedia article Lisa Ann Walter, licensed under CC-BY-SA, full list of contributors on Wikipedia.",
        "birthday": "1963-08-03",
        "deathday": null,
        "gender": 1,
        "homepage": null,
        "id": 4494,
        "imdb_id": "nm0910076",
        "known_for_department": "Acting",
        "name": "Lisa Ann Walter",
        "place_of_birth": "Silver Spring, Maryland, USA",
        "popularity": 54.729,
        "profile_path": "/3xeMzT5zOC0UM9DgHne3oGZmf1R.jpg"
    },
    {
        "adult": false,
        "also_known_as": ["גל גדות", "Галь Гадот", "盖尔·加朵", "กัล กาด็อต", "ガル・ガドット", "غال غادوت", "蓋兒加朵", "갤 가돗", "Γκαλ Γκαντότ-Βαρσάνο", "Γκαλ Γκαντότ", "Gal Gadot Varsano"],
        "biography": "Gal Gadot (born: April 30, 1985) is an Israeli actress and model. She was born in Rosh Ha'ayin, Israel, to an Ashkenazi Jewish family (from Poland, Austria, Germany, and Czechoslovakia). She served in the IDF for two years, and won the Miss Israel title in 2004.\n\nGal began modeling in the late 2000s, and made her film debut in the fourth film of the Fast and Furious franchise, Fast & Furious (2009), as Gisele, an associate of the film's lead villain. Her role was expanded in the sequels Fast Five (2011) and Fast & Furious 6 (2013), in which her character was romantically linked to Han Seoul-Oh (Sung Kang). In the films, Gal performed her own stunts. She also appeared in the 2010 films Date Night (2010) and Knight and Day (2010). In early December 2013, Gal was cast as Wonder Woman in the DC Extended Universe.\n\nGal is a motorcycle enthusiast, and owns a black 2006 Ducati Monster-S2R. She has been married to Yaron Versano since September 28, 2008. They have one child.",
        "birthday": "1985a04-30",
        "deathday": null,
        "gender": 1,
        "homepage": "http://www.galgadot.com",
        "id": 90633,
        "imdb_id": "nm2933757",
        "known_for_department": "Acting",
        "name": "Gal Gadot",
        "place_of_birth": "Rosh Ha'ayin, Israel",
        "popularity": 47.845,
        "profile_path": "/xu1l9WmNY1XYZyJ3M2gvGqCCDGS.jpg"
    },

    {
        "adult": false,
        "also_known_as": ["Thomas Jeffrey Hanks", "Том Хэнкс", "توم هانكس", "トム・ハンクス", "톰 행크스", "ทอม แฮงส์", "汤姆·汉克斯", "Том Генкс", "Том Хенкс", "Томас Джеффрі Генкс", "Τομ Χανκς", "टॉम हैंक्स", "ടോം ഹാങ്ക്സ്", "湯姆‧漢克斯"],
        "biography": "Thomas Jeffrey Hanks (born July 9, 1956) is an American actor and filmmaker. Known for both his comedic and dramatic roles, Hanks is one of the most popular and recognizable film stars worldwide, and is widely regarded as an American cultural icon.\n\nHanks made his breakthrough with leading roles in the comedies Splash (1984) and Big (1988). He won two consecutive Academy Awards for Best Actor for starring as a gay lawyer suffering from AIDS in Philadelphia (1993) and a young man with below-average IQ in Forrest Gump (1994). Hanks collaborated with film director Steven Spielberg on five films: Saving Private Ryan (1998), Catch Me If You Can (2002), The Terminal (2004), Bridge of Spies (2015), and The Post (2017), as well as the 2001 miniseries Band of Brothers, which launched him as a director, producer, and screenwriter.\n\nHanks' other notable films include the romantic comedies Sleepless in Seattle (1993) and You've Got Mail (1998); the dramas Apollo 13 (1995), The Green Mile (1999), Cast Away (2000), Road to Perdition (2002), and Cloud Atlas (2012); and the biographical dramas Saving Mr. Banks (2013), Captain Phillips (2013), Sully (2016), and A Beautiful Day in the Neighborhood (2019). He has also appeared as the title character in the Robert Langdon film series, and has voiced Sheriff Woody in the Toy Story film series.\n\nDescription above from the Wikipedia article Tom Hanks, licensed under CC-BY-SA, full list of contributors on Wikipedia.",
        "birthday": "1956-07-09",
        "deathday": null,
        "gender": 2,
        "homepage": null,
        "id": 31,
        "imdb_id": "nm0000158",
        "known_for_department": "Acting",
        "name": "Tom Hanks",
        "place_of_birth": "Concord, California, USA",
        "popularity": 26.081,
        "profile_path": "/zVyoR2ZNiVGymjZK4MMJHIdpxoW.jpg"
    },

    {
        "adult": false,
        "also_known_as": [" Lucas York Black "],
        "biography": "Lucas York Black (born November 29, 1982) is an American film and television actor. He is known for his roles in the CBS television series American Gothic as well as roles in films such as Sling Blade, Jarhead, Friday Night Lights, The Fast and the Furious: Tokyo Drift, Legion and Get Low.\n\nDescription above from the Wikipedia article Lucas Black , licensed under CC-BY-SA, full list of contributors on Wikipedia.",
        "birthday": "1982-11-29",
        "deathday": null,
        "gender": 2,
        "homepage": null,
        "id": 155,
        "imdb_id": "nm0085407",
        "known_for_department": "Acting",
        "name": "Lucas Black",
        "place_of_birth": "Speake, Alabama, USA",
        "popularity": 3.011,
        "profile_path": "/w2oImwC4Y0RDtyvaKGTCFCKsvwh.jpg"
    },
    //4
    //5
    {
        "adult": false,
        "also_known_as": ["برد پیت", "Бред Пітт", "Брэд Питт", "畢·彼特", "ブラッド・ピット", "브래드 피트", "براد بيت", "แบรด พิตต์", "William Bradley \"Brad\" Pitt", "William Bradley Pitt", "Μπραντ Πιτ", "布拉德·皮特", "Breds Pits"],
        "biography": "William Bradley Pitt is an American actor and film producer. He has received multiple awards, including two Golden Globe Awards and an Academy Award for his acting, in addition to another Academy Award and a Primetime Emmy Award as producer under his production company, Plan B Entertainment. Pitt first gained recognition as a cowboy hitchhiker in the road movie Thelma & Louise (1991). His first leading roles in big-budget productions came with the drama films A River Runs Through It (1992) and Legends of the Fall (1994), and the horror film Interview with the Vampire (1994). He gave critically acclaimed performances in the crime thriller Seven (1995) and the science fiction film 12 Monkeys (1995), the latter earning him a Golden Globe Award for Best Supporting Actor and an Academy Award nomination. Pitt starred in Fight Club (1999) and the heist film Ocean's Eleven (2001), as well as its sequels, Ocean's Twelve (2004) and Ocean's Thirteen (2007). His greatest commercial successes have been Ocean's Eleven (2001), Troy (2004), Mr. & Mrs. Smith (2005), World War Z (2013), and Once Upon a Time in Hollywood (2019), for which he won a second Golden Globe Award and the Academy Award for Best Supporting Actor. Pitt's other Academy Award nominated performances were in The Curious Case of Benjamin Button (2008) and Moneyball (2011). He produced The Departed (2006) and 12 Years a Slave (2013), both of which won the Academy Award for Best Picture, and also The Tree of Life (2011), Moneyball (2011), and The Big Short (2015), all of which were nominated for Best Picture. As a public figure, Pitt has been cited as one of the most influential and powerful people in the American entertainment industry. For a number of years, he was cited as the world's most attractive man by various media outlets, and his personal life is the subject of wide publicity. From 2000 to 2005, he was married to the actress Jennifer Aniston, and from 2014 to 2019, he was married to the actress Angelina Jolie. Pitt and Jolie have six children together, three of whom were adopted internationally.",
        "birthday": "1963-12-18",
        "deathday": null,
        "gender": 2,
        "homepage": null,
        "id": 287,
        "imdb_id": "nm0000093",
        "known_for_department": "Acting",
        "name": "Brad Pitt",
        "place_of_birth": "Shawnee, Oklahoma, USA",
        "popularity": 20.432,
        "profile_path": "/oTB9vGIBacH5aQNS0pUM74QSWuf.jpg"
    },
    //6
    {
        "adult": false,
        "also_known_as": ["Том Круз", "トム・クルーズ", "ทอม ครูซ", "湯姆·克魯斯", "톰 크루즈", "توم كروز", "Thomas Cruise Mapother IV", "Τομ Κρουζ", "טום קרוז", "Thomas \"Tom\" Cruise", "汤姆·克鲁斯", "TC"],
        "biography": "An American actor and filmmaker. He has been nominated for three Academy Awards and has won three Golden Globe Awards. He started his career at age 19 in the 1981 film Endless Love. After portraying supporting roles in Taps (1981) and The Outsiders (1983), his first leading role was in Risky Business, released in August 1983. Cruise became a full-fledged movie star after starring as Pete \"Maverick\" Mitchell in Top Gun (1986). He has since 1996 been well known for his role as secret agent Ethan Hunt in the Mission: Impossible film series. One of the biggest movie stars in Hollywood, Cruise has starred in many successful films, including The Color of Money (1986), Cocktail (1988), Rain Man (1988), Born on the Fourth of July (1989), Far and Away(1992), A Few Good Men (1992), The Firm (1993), Interview with the Vampire: The Vampire Chronicles (1994), Jerry Maguire (1996), Eyes Wide Shut (1999), Magnolia (1999), Vanilla Sky (2001), Minority Report (2002),The Last Samurai (2003), Collateral (2004), War of the Worlds (2005), Lions for Lambs (2007), Valkyrie (2008), Knight and Day (2010), Jack Reacher (2012), Oblivion (2013), and Edge of Tomorrow (2014). In 2012, Cruise was Hollywood's highest-paid actor. Fifteen of his films grossed over $100 million domestically; twenty-one have grossed in excess of $200 million worldwide. Cruise is known for his support for the Church of Scientology and its affiliated social programs.",
        "birthday": "1962-07-03",
        "deathday": null,
        "gender": 2,
        "homepage": "http://www.tomcruise.com",
        "id": 500,
        "imdb_id": "nm0000129",
        "known_for_department": "Acting",
        "name": "Tom Cruise",
        "place_of_birth": "Syracuse, New York, USA",
        "popularity": 24.584,
        "profile_path": "/gThaIXgpCm3PCiXwFNDBJCme85y.jpg"
    },
    //7
    {
        "adult": false,
        "also_known_as": ["Брюс Уиллис", "ブルース・ウィリス", "بروس ويليس", "브루스 윌리스", "บรูซ วิลลิส", "ברוס וויליס", "Walter Bruce Willis", "Bruno", "Γουόλτερ Μπρους Γουίλις", "Μπρους Γουίλις", "布鲁斯·威利斯"],
        "biography": "An American actor and producer. His career began in television in the 1980s and has continued both in television and film since, including comedic, dramatic, and action roles. He is well known for the role of John McClane in the Die Hard series. Willis was born in Idar-Oberstein, West Germany, the son of a Kassel-born German, Marlene, who worked in a bank, and David Willis, an American soldier. Willis is the eldest of four children. At the premiere for the film Stakeout, Willis met actress Demi Moore. They married on November 21, 1987 and had three daughters before the couple divorced on October 18, 2000. Since the divorce he has dated models Maria Bravo Rosado and Emily Sandberg; he was engaged to Brooke Burns until they broke up in 2004 after ten months together. He married Emma Heming on March 21, 2009.",
        "birthday": "1955-03-19",
        "deathday": null,
        "gender": 2,
        "homepage": null,
        "id": 62,
        "imdb_id": "nm0000246",
        "known_for_department": "Acting",
        "name": "Bruce Willis",
        "place_of_birth": "Idar-Oberstein, Germany",
        "popularity": 27.245,
        "profile_path": "/A1XBu3CffBpSK8HEIJM8q7Mn4lz.jpg"
    },
    //8
    {
        "adult": false,
        "also_known_as": ["Леонардо ДиКаприо", "ليوناردو دي كابريو", "레오나르도 디카프리오", "レオナルド・ディカプリオ", "ลีโอนาร์โด ดิแคพรีโอ", "莱昂纳多·迪卡普里奥", "Leo DiCaprio", "Leonardo Retardo", "Leonardo Wilhelm DiCaprio", "Λεονάρντο Ντι Κάπριο", "Ντι Κάπριο", "Леонардо Ді Капріо", "Леонардо ДіКапріо", "לאונרדו דיקפריו"],
        "biography": "Leonardo DiCaprio (born November 11, 1974) is an American actor, film producer, and environmental activist.\n\nHe began his film career by starring as Josh in Critters 3 before starring in the film adaptation of the memoir This Boy's Life (1993) alongside Robert De Niro. DiCaprio was praised for his supporting role in the drama What's Eating Gilbert Grape (1993), and gained public recognition with leading roles in the drama The Basketball Diaries (1995) and the romantic drama Romeo + Juliet (1996), before achieving international fame with James Cameron's epic romance Titanic (1997) He has been nominated for six Academy Awards—five for acting and one for producing—and in 2016, he won the Academy Award for Best Actor for The Revenant.\n\nDiCaprio is the founder of his own production company, named Appian Way Productions. He is also a committed environmentalist.",
        "birthday": "1974-11-11",
        "deathday": null,
        "gender": 2,
        "homepage": "http://leonardodicaprio.com",
        "id": 6193,
        "imdb_id": "nm0000138",
        "known_for_department": "Acting",
        "name": "Leonardo DiCaprio",
        "place_of_birth": "Los Angeles, California, USA",
        "popularity": 14.747,
        "profile_path": "/wo2hJpn04vbtmh0B9utCFdsQhxM.jpg"
    },
    //9
    {
        "adult": false,
        "also_known_as": ["Scarlett Johanssen", "Скарлетт Йоганссон", "Скарлетт Йоханссон", "Scarlett Ingrid Johansson", "스칼릿 조핸슨", "سكارليت جوهانسون", "史嘉蕾·喬韓森", "สการ์เลตต์ โจแฮนส์สัน", "スカーレット・ヨハンソン", "斯嘉丽·约翰逊", "스칼렛 요한슨", "Σκάρλετ Τζοχάνσον", "اسکارلت جوهانسون"], "biography": "Scarlett Johansson, born November 22, 1984, is an American actress, model and singer. She made her film debut in North (1994) and was later nominated for the Independent Spirit Award for Best Female Lead for her performance in Manny & Lo (1996), garnering further acclaim and prominence with roles in The Horse Whisperer (1998) and Ghost World (2001). She shifted to adult roles with her performances in Girl with a Pearl Earring (2003) and Sofia Coppola's Lost in Translation (2003), for which she won a BAFTA award for Best Actress in a Leading Role; both films earned her Golden Globe Award nominations as well.\n\nA role in A Love Song for Bobby Long (2004) earned Johansson her third Golden Globe for Best Actress nomination. Johansson garnered another Golden Globe nomination for Best Supporting Actress with her role in Woody Allen's Match Point (2005). She has played the Marvel comic book character Black Widow/Natasha Romanoff in Iron Man 2 (2010), The Avengers (2012), and Captain America: The Winter Soldier (2014), Avengers: Age of Ultron (2015), Captain America: Civil War (2016), Avengers: Infinity War (2018), Avengers: Endgame (2019), and Black Widow (2020). The 2010 Broadway revival of Arthur Miller's A View From the Bridge won Johansson the Tony Award for Best Performance by a Featured Actress in a Play. As a singer, Johansson has released two albums, Anywhere I Lay My Head and Break Up.\n\nJohansson was nominated for two Academy Awards in 2020 for her work in Marriage Story (2019), and Jojo Rabbit (2019).  Johansson was born in New York City. Her father, Karsten Johansson, is a Danish-born architect, and her paternal grandfather, Ejner Johansson, was a screenwriter and director. Her mother, Melanie Sloan, a producer, comes from an Ashkenazi Jewish family from the Bronx. Johansson has an older sister, Vanessa, who is an actress; an older brother, Adrian; a twin brother, Hunter (who appeared in the film Manny & Lo with Scarlett); and a half-brother, Christian, from her father's re-marriage .",
        "birthday": "1984-11-22",
        "deathday": null,
        "gender": 1,
        "homepage": null,
        "id": 1245,
        "imdb_id": "nm0424060",
        "known_for_department": "Acting",
        "name": "Scarlett Johansson",
        "place_of_birth": "New York City, New York, USA",
        "popularity": 31.97,
        "profile_path": "/6NsMbJXRlDZuDzatN2akFdGuTvx.jpg"
    },
    //10
    {
        "adult": false,
        "also_known_as": ["Марго Роббі", "Марго Робби", "มาร์โก ร็อบบี", "瑪歌·羅比", "마고 로비", "مارجوت روبي", "マーゴット・ロビー", "Марго Роби", "Margot Elise Robbie", "Μάργκοτ Ελίς Ρόμπι", "Μάργκοτ Ρόμπι", "玛格特·罗比", "Марґо Роббі"],
        "biography": "Margot Elise Robbie (born 2 July 1990) is an Australian actress and producer. She has received nominations for two Academy Awards and five BAFTA Awards. In 2017, Time magazine named her one of the 100 most influential people in the world, and in 2019, she was ranked among the world's highest-paid actresses.\n\nRobbie studied drama at Somerset College and began her career in Australian independent films in the late 2000s, before working in the soap opera Neighbours (2008–2011). After moving to America, she starred in the ABC drama series Pan Am (2011–2012) and had her breakthrough role in Martin Scorsese's black comedy film The Wolf of Wall Street (2013). Robbie's profile continued to grow with starring roles as a grifter in Focus (2015), Jane Porter in The Legend of Tarzan (2016), and Harley Quinn in the DC Extended Universe, beginning with Suicide Squad (2016).\n\nRobbie garnered critical acclaim and nominations for the BAFTA Award and Academy Award for Best Actress for portraying the disgraced figure skater Tonya Harding in the biopic I, Tonya (2017). This acclaim continued for her roles as Queen Elizabeth I in the period drama Mary Queen of Scots (2018), Sharon Tate in the comedy-drama Once Upon a Time in Hollywood (2019), and a fictional Fox News employee in the drama Bombshell (2019). She received BAFTA Award nominations for all three and a nomination for the Academy Award for Best Supporting Actress for the lattermost.\n\nRobbie is married to the filmmaker Tom Ackerley. They are among the founders of the production company LuckyChap Entertainment, under which she has produced some of her own films, as well as the television series Dollface (2019–present).",
        "birthday": "1990-07-02",
        "deathday": null,
        "gender": 1,
        "homepage": null,
        "id": 234352,
        "imdb_id": "nm3053338",
        "known_for_department": "Acting",
        "name": "Margot Robbie",
        "place_of_birth": "Dalby, Queensland, Australia",
        "popularity": 23.061,
        "profile_path": "/mzwuoK7i418q28KI8cQIFzKcWjg.jpg"
    },
]